%-- 4/20/10 11:53 AM --%
% any arbitary wave can be generated by this code
clc;
clear all;
close all;
x=0:1024;
x=x/64;
y=exp(-x).*sin(10*x);
val=int32( y(1:256)*(127) );
for i=1:128
    disp([' when ' num2str(i-1) ' =>']);
    disp(['table_value := ' num2str(val(i)) ';']);
%%disp(val(2*i));
j(i)=val(2*i);
end;
stem(j);